"use client";

import Link from "next/link";

import { PrimaryButton, SecondaryButton } from "../components/Buttons";
import { useLanguage } from "../components/providers/LanguageProvider";
import { useCopy } from "../lib/copy";

type LangKey = "en" | "es";

const copy = {
  en: {
    heroTitle: "AI agents that stay on duty when your team logs off.",
    heroSubtitle:
      "OnDuty handles customer questions 24/7 through a simple web chat. Built for small and medium businesses. WhatsApp & Telegram coming soon.",
    heroPrimaryCtaTry: "Try our agent",
    heroPrimaryCtaTrySub: "See a live demo in your browser in under a minute.",
    heroPrimaryCtaSignup: "Sign up for free",
    heroPrimaryCtaSignupSub: "Start a 3-day free trial. Extend to 15 days when you add your card.",
    heroSecondaryLink: "See use cases",
    whoForItems: [
      "Hotels & short-term rentals",
      "Restaurants & delivery",
      "Clinics & practices",
      "Retail & e-commerce",
      "Public offices",
      "Fintech & banks",
    ],
    howTitle: "How OnDuty works",
    howSteps: [
      {
        title: "Connect your website chat",
        text: "Get a hosted chat link or paste a small snippet on your site. No dev team required.",
      },
      {
        title: "Teach it your business",
        text: "Load your FAQs, policies and key pages so the agent answers like someone on your team.",
      },
      {
        title: "Go live & monitor",
        text: "Turn it on, watch conversations in real time, and jump in whenever a human touch is needed.",
      },
    ],
    whyTitle: "Why teams use OnDuty",
    whyFeatures: [
      {
        title: "24/7 coverage, no shifts",
        text: "Your agent stays online when the phones are off and your team is sleeping.",
      },
      {
        title: "Built for support and pre-sales",
        text: "Answers common questions, captures intent and gets people ready to talk to a human.",
      },
      {
        title: "Multi-language from day one",
        text: "English and Spanish support out of the box, with more languages coming soon.",
      },
      {
        title: "Analytics you can actually act on",
        text: "See volume, busiest hours, resolution rate and what people ask the most.",
      },
      {
        title: "Humans can take over anytime",
        text: "Your team can jump into any conversation with full context and history.",
      },
      {
        title: "Secure, multi-tenant SaaS",
        text: "Each business has its own workspace, data and permissions.",
      },
    ],
    useCasesTitle: "Use cases",
    useCases: [
      {
        title: "Hotels & short-term rentals",
        bullets: [
          "Answer booking questions before they leave your site.",
          "Share check-in, late arrival and amenities info instantly.",
          "Reduce repetitive “what’s the Wi-Fi?” or “where do I park?” messages.",
        ],
      },
      {
        title: "Restaurants & delivery",
        bullets: [
          "Handle opening hours, menu questions and delivery areas.",
          "Route special requests to your team when needed.",
          "Reduce phone calls at peak hours.",
        ],
      },
      {
        title: "Clinics, dentists & practices",
        bullets: [
          "Answer basic questions before a visit.",
          "Collect appointment requests and contact details.",
          "Set expectations around prep, timings and follow-ups.",
        ],
      },
      {
        title: "Retail & e-commerce",
        bullets: [
          "Help people find the right product faster.",
          "Answer questions on sizes, shipping and returns.",
          "Reduce cart abandonment from unanswered doubts.",
        ],
      },
      {
        title: "Fintech & banking",
        bullets: [
          "Answer simple “how does this work?” questions.",
          "Guide users through basic flows and limits.",
          "Escalate sensitive issues to your human team.",
        ],
      },
      {
        title: "Public offices",
        bullets: [
          "Share opening hours, locations and requirements.",
          "Explain step-by-step processes in clear language.",
          "Reduce queues generated by simple questions.",
        ],
      },
    ],
    analyticsTitle: "Analytics and reports you can act on",
    analyticsIntro: "See your support reality without exporting to Excel.",
    analyticsBullets: [
      {
        title: "Conversation volume & busiest hours",
        text: "Know when you really need people on duty.",
      },
      {
        title: "Topics and questions",
        text: "Understand what guests, patients or customers care about.",
      },
      {
        title: "Per-customer history",
        text: "Every conversation in one place when a human jumps in.",
      },
      {
        title: "Email reports",
        text: "Weekly for every plan, monthly and quarterly on higher tiers.",
      },
      {
        title: "Suspicious activity alerts",
        text: "Get notified when someone abuses or tries to game your agent.",
      },
    ],
    csVsSalesTitle: "Customer service agents today. Sales agents soon.",
    csCardTitle: "Customer service agents",
    csCardTag: "Live now",
    csCardText:
      "Web chat agents that answer questions, handle basic support and keep people informed when your team is offline.\n\n- Live on web chat today\n- Perfect for FAQs, bookings and simple troubleshooting\n- Designed for hotels, restaurants, clinics, retail and more",
    salesCardTitle: "Sales agents (coming soon)",
    salesCardTag: "Coming soon",
    salesCardText:
      "Sales-first agents for WhatsApp and Telegram. Capture leads, qualify them and hand them to your reps once messaging APIs are ready.\n\n- Designed for follow-ups and reminders\n- Built for WhatsApp and Telegram once integrations are live\n- Enterprise customers get early access",
    pricingTitle: "Pricing for Customer Service agents",
    pricingSubtitle: "Start in minutes. 3-day free trial without a card, or 15 days when you add your card.",
    pricingPlans: [
      {
        id: "basic",
        name: "Basic",
        label: "For small teams getting started with AI support.",
        price: "$20 / month",
        popular: false,
        bullets: [
          "Up to 200 conversations / month",
          "1 workspace, 1 brand or location",
          "1 admin seat",
          "Hosted chat page + simple embed",
          "Basic analytics (volume, resolution rate, response time)",
          "Weekly email report",
          "3-day free trial (no card) or 15 days (with card)",
        ],
      },
      {
        id: "growth",
        name: "Growth",
        label: "For growing teams that handle more volume.",
        price: "$40 / month",
        popular: true,
        bullets: [
          "Up to 500 conversations / month",
          "1 workspace, up to 2 brands/locations",
          "Up to 3 admin seats",
          "Everything in Basic, plus:",
          "Advanced analytics (by channel, time of day, basic tagging)",
          "Saved replies and FAQ library",
          "Weekly and monthly email reports",
        ],
      },
      {
        id: "premium",
        name: "Premium",
        label: "For larger companies that live in chat.",
        price: "$60 / month",
        popular: false,
        bullets: [
          "Up to 1000 conversations / month",
          "1 workspace, up to 3 brands/locations",
          "Up to 5 admin seats",
          "Everything in Growth, plus:",
          "Deeper analytics (top topics, busiest hours, languages)",
          "Usage and suspicious-activity alerts",
          "Weekly, monthly and quarterly email reports",
          "Priority support",
        ],
      },
      {
        id: "enterprise",
        name: "Enterprise",
        label: "For teams that need custom volumes and support.",
        price: "Contact us",
        popular: false,
        bullets: [
          "Custom conversation volume (1000+ / month)",
          "Flexible brands and locations",
          "Dedicated onboarding and data setup",
          "Security and compliance review",
          "Early access to new channels (WhatsApp, Telegram, Instagram) as they launch",
          "Custom reports and SLAs",
        ],
        ctaLabel: "Contact sales",
      },
    ],
    salesComingTitle: "Sales agents – coming soon",
    salesComingText:
      "Sales-first agents built for WhatsApp and Telegram. Capture leads, qualify them and hand them to your sales team once messaging integrations are live.\n\nJoin the waitlist to be the first to test:\n- Lead capture on chat instead of forms\n- Automated follow-ups and reminders\n- Handoff into your CRM or human reps",
    salesComingCta: "Join the waitlist",
    faqTitle: "FAQ",
    faqItems: [
      {
        question: "Can I try OnDuty for free?",
        answer:
          "Yes. You can start with a 3-day free trial without a card. If you add your card during signup, you get a 15-day trial and your plan starts only if you decide to keep using it.",
      },
      {
        question: "What happens if I go over my conversation limit?",
        answer:
          "We don’t suddenly shut you down. For now, we’ll notify you when you get close to your limit so you can upgrade or talk to us about a better fit.",
      },
      {
        question: "Do I need developers to install it?",
        answer:
          "No. You get a hosted chat link that works out of the box and a simple embed snippet if you want the chat inside your site.",
      },
      {
        question: "Does it work with WhatsApp today?",
        answer:
          "Web chat is live today. WhatsApp and Telegram are part of our roadmap and will roll out once we’re aligned with the official APIs. Enterprise customers get early access.",
      },
      {
        question: "Which languages are supported?",
        answer:
          "We support English and Spanish from day one. If you need another language, let us know and we’ll prioritize it.",
      },
    ],
    finalCtaTitle: "Ready to have someone on duty 24/7?",
    finalCtaText:
      "Spin up your first agent in minutes, see real conversations and decide if it earns its place in your stack.",
    finalCtaPrimary: "Try our agent",
    finalCtaSecondary: "Sign up for free",
  },
  es: {
    heroTitle: "Agentes de IA siempre de turno, aunque tu equipo no lo esté.",
    heroSubtitle:
      "OnDuty atiende preguntas de tus clientes 24/7 con un chat web sencillo. Diseñado para pymes. Integración con WhatsApp y Telegram muy pronto.",
    heroPrimaryCtaTry: "Probar el agente",
    heroPrimaryCtaTrySub: "Mira una demo en vivo en tu navegador en menos de un minuto.",
    heroPrimaryCtaSignup: "Crear mi cuenta gratis",
    heroPrimaryCtaSignupSub: "Empieza con 3 días gratis. Extiende a 15 días cuando agregas tu tarjeta.",
    heroSecondaryLink: "Ver casos de uso",
    whoForItems: [
      "Hoteles y rentas cortas",
      "Restaurantes y domicilios",
      "Clínicas y consultorios",
      "Retail y e-commerce",
      "Oficinas públicas",
      "Fintech y bancos",
    ],
    howTitle: "Cómo funciona OnDuty",
    howSteps: [
      {
        title: "Conecta el chat en tu web",
        text: "Usa un enlace hospedado o pega un pequeño código en tu sitio. Sin necesidad de equipo técnico.",
      },
      {
        title: "Enséñale tu negocio",
        text: "Carga tus FAQs, políticas y páginas clave para que el agente responda como alguien de tu equipo.",
      },
      {
        title: "Actívalo y monitorea",
        text: "Enciéndelo, mira las conversaciones en tiempo real y entra cuando se necesite atención humana.",
      },
    ],
    whyTitle: "Por qué los equipos usan OnDuty",
    whyFeatures: [
      {
        title: "Cobertura 24/7, sin turnos",
        text: "Tu agente sigue atendiendo cuando apagan el teléfono y tu equipo duerme.",
      },
      {
        title: "Pensado para soporte y preventa",
        text: "Responde las dudas frecuentes, capta intención y deja a la persona lista para hablar con tu equipo.",
      },
      {
        title: "Multilenguaje desde el día uno",
        text: "Soporte en inglés y español desde el inicio, con más idiomas en camino.",
      },
      {
        title: "Analítica que sí sirve",
        text: "Mira volumen, horas pico, tasa de resolución y qué preguntan más tus clientes.",
      },
      {
        title: "Tu equipo puede tomar el control",
        text: "Tu equipo entra en cualquier conversación con todo el contexto e historial.",
      },
      {
        title: "SaaS seguro y multi-empresa",
        text: "Cada negocio tiene su propio espacio, datos y permisos separados.",
      },
    ],
    useCasesTitle: "Casos de uso",
    useCases: [
      {
        title: "Hoteles y rentas cortas",
        bullets: [
          "Responde dudas de reserva antes de que la persona abandone tu sitio.",
          "Comparte info de check-in, llegadas tarde y amenidades al instante.",
          "Reduce mensajes repetidos del tipo “¿cuál es el Wi-Fi?” o “¿dónde parqueo?”.",
        ],
      },
      {
        title: "Restaurantes y domicilios",
        bullets: [
          "Atiende horarios, preguntas de menú y zonas de entrega.",
          "Escala pedidos especiales a tu equipo cuando haga falta.",
          "Reduce llamadas en horas pico.",
        ],
      },
      {
        title: "Clínicas, dentistas y consultorios",
        bullets: [
          "Responde preguntas básicas antes de la cita.",
          "Recoge solicitudes de cita y datos de contacto.",
          "Aclara preparación, tiempos y próximos pasos.",
        ],
      },
      {
        title: "Retail y e-commerce",
        bullets: [
          "Ayuda a encontrar el producto correcto más rápido.",
          "Atiende tallas, envíos y devoluciones.",
          "Disminuye carritos abandonados por falta de información.",
        ],
      },
      {
        title: "Fintech y banca",
        bullets: [
          "Responde dudas simples de “¿cómo funciona?”.",
          "Guía pasos básicos y explica límites y condiciones.",
          "Escala temas sensibles a tu equipo humano.",
        ],
      },
      {
        title: "Oficinas públicas",
        bullets: [
          "Informa horarios, sedes y requisitos.",
          "Explica procesos paso a paso con lenguaje claro.",
          "Reduce filas generadas por preguntas sencillas.",
        ],
      },
    ],
    analyticsTitle: "Analítica y reportes que sí sirven",
    analyticsIntro: "Entiende la realidad de tu soporte sin exportar nada a Excel.",
    analyticsBullets: [
      {
        title: "Volumen de conversaciones y horas pico",
        text: "Para saber cuándo de verdad necesitas gente conectada.",
      },
      {
        title: "Temas y preguntas frecuentes",
        text: "Entiende qué es lo que más preocupa a tus clientes y huéspedes.",
      },
      {
        title: "Historial por cliente",
        text: "Todas las conversaciones en un solo lugar cuando entra alguien de tu equipo.",
      },
      {
        title: "Reportes por correo",
        text: "Semanales en todos los planes; mensuales y trimestrales en los planes superiores.",
      },
      {
        title: "Alertas de actividad sospechosa",
        text: "Te avisamos cuando alguien intenta abusar o “hackear” al agente.",
      },
    ],
    csVsSalesTitle: "Agentes de servicio hoy. Agentes de ventas muy pronto.",
    csCardTitle: "Agentes de servicio al cliente",
    csCardTag: "Disponible ahora",
    csCardText:
      "Agentes en chat web que responden preguntas, resuelven dudas básicas y mantienen informados a tus clientes cuando tu equipo está fuera de línea.\n\n- Activo hoy en chat web\n- Ideal para FAQs, reservas y soporte sencillo\n- Diseñado para hoteles, restaurantes, clínicas, retail y más",
    salesCardTitle: "Agentes de ventas (próximamente)",
    salesCardTag: "Muy pronto",
    salesCardText:
      "Agentes pensados para ventas en WhatsApp y Telegram. Captan leads, los califican y los entregan a tu equipo comercial cuando las APIs de mensajería estén listas.\n\n- Pensados para seguimientos y recordatorios\n- Construidos para WhatsApp y Telegram cuando las integraciones estén en producción\n- Clientes Enterprise tendrán acceso anticipado",
    pricingTitle: "Precios para agentes de servicio al cliente",
    pricingSubtitle: "Empieza en minutos. 3 días gratis sin tarjeta, o 15 días cuando agregas tu tarjeta.",
    pricingPlans: [
      {
        id: "basic",
        name: "Básico",
        label: "Para equipos pequeños que quieren empezar con soporte por IA.",
        price: "USD $20 / mes",
        popular: false,
        bullets: [
          "Hasta 200 conversaciones al mes",
          "1 espacio de trabajo, 1 marca o ubicación",
          "1 usuario administrador",
          "Chat hospedado + código de inserción sencillo",
          "Analítica básica (volumen, resolución, tiempo de respuesta)",
          "Reporte semanal por correo",
          "Prueba gratis de 3 días (sin tarjeta) o 15 días (con tarjeta)",
        ],
      },
      {
        id: "growth",
        name: "Crecimiento",
        label: "Para equipos en expansión con más volumen.",
        price: "USD $40 / mes",
        popular: true,
        bullets: [
          "Hasta 500 conversaciones al mes",
          "1 espacio de trabajo, hasta 2 marcas/ubicaciones",
          "Hasta 3 usuarios administradores",
          "Todo lo del plan Básico, más:",
          "Analítica avanzada (por canal, hora del día, tags básicos)",
          "Respuestas guardadas y biblioteca de FAQs",
          "Reportes semanales y mensuales por correo",
        ],
      },
      {
        id: "premium",
        name: "Premium",
        label: "Para empresas que viven en el chat.",
        price: "USD $60 / mes",
        popular: false,
        bullets: [
          "Hasta 1000 conversaciones al mes",
          "1 espacio de trabajo, hasta 3 marcas/ubicaciones",
          "Hasta 5 usuarios administradores",
          "Todo lo del plan Crecimiento, más:",
          "Analítica más profunda (temas principales, horas pico, idiomas)",
          "Alertas de uso y de actividad sospechosa",
          "Reportes semanales, mensuales y trimestrales por correo",
          "Soporte prioritario",
        ],
      },
      {
        id: "enterprise",
        name: "Enterprise",
        label: "Para equipos que necesitan volúmenes y soporte a la medida.",
        price: "Contáctanos",
        popular: false,
        bullets: [
          "Volumen de conversaciones a la medida (más de 1000 al mes)",
          "Marcas y ubicaciones flexibles",
          "Onboarding dedicado y configuración de datos",
          "Revisión de seguridad y cumplimiento",
          "Acceso anticipado a nuevos canales (WhatsApp, Telegram, Instagram) a medida que salgan",
          "Reportes y SLAs personalizados",
        ],
        ctaLabel: "Hablar con ventas",
      },
    ],
    salesComingTitle: "Agentes de ventas – muy pronto",
    salesComingText:
      "Agentes enfocados en ventas para WhatsApp y Telegram. Captan leads, los califican y los entregan a tu equipo comercial cuando las integraciones de mensajería estén listas.\n\nSúmate a la lista de espera para ser de los primeros en probar:\n- Captura de leads en chat en lugar de formularios\n- Seguimientos y recordatorios automáticos\n- Entrega directa a tu CRM o a tu equipo de ventas",
    salesComingCta: "Unirme a la lista de espera",
    faqTitle: "Preguntas frecuentes",
    faqItems: [
      {
        question: "¿Puedo probar OnDuty gratis?",
        answer:
          "Sí. Puedes empezar con una prueba gratis de 3 días sin tarjeta. Si agregas tu tarjeta al registrarte, obtienes 15 días de prueba y tu plan solo comienza si decides seguir usando la plataforma.",
      },
      {
        question: "¿Qué pasa si me paso del límite de conversaciones?",
        answer:
          "No te vamos a apagar de repente. Por ahora, te avisamos cuando te acerques a tu límite para que puedas subir de plan o hablar con nosotros para buscar una mejor opción.",
      },
      {
        question: "¿Necesito desarrolladores para instalarlo?",
        answer:
          "No. Tienes un enlace de chat hospedado que funciona de inmediato y un código de inserción sencillo si quieres tener el chat dentro de tu sitio.",
      },
      {
        question: "¿Funciona ya con WhatsApp?",
        answer:
          "Hoy funciona en chat web. WhatsApp y Telegram están en nuestra hoja de ruta y los activaremos cuando estemos alineados con las APIs oficiales. Los clientes Enterprise tendrán acceso anticipado.",
      },
      {
        question: "¿Qué idiomas soporta?",
        answer:
          "Soportamos inglés y español desde el día uno. Si necesitas otro idioma, avísanos y lo priorizamos.",
      },
    ],
    finalCtaTitle: "¿Listo para tener a alguien de turno 24/7?",
    finalCtaText:
      "Crea tu primer agente en minutos, mira conversaciones reales y decide si se gana su lugar en tu stack.",
    finalCtaPrimary: "Probar el agente",
    finalCtaSecondary: "Crear mi cuenta gratis",
  },
} as const satisfies Record<LangKey, unknown>;

export default function LandingPage() {
  const { language } = useLanguage();
  const t = useCopy();
  const lang: LangKey = language === "es" ? "es" : "en";
  const c = (copy as Record<LangKey, (typeof copy)[LangKey]>)[lang];

  const splitList = (text: string) =>
    text.split("\n").filter((line) => line.trim() !== "");

  const useCaseIcons: Record<string, string> = {
    "Hotels & short-term rentals": "🏨",
    "Restaurants & delivery": "🍽️",
    "Restaurantes & delivery": "🍽️",
    "Hoteles y rentas cortas": "🏨",
    "Clinics, dentists & practices": "🩺",
    "Clínicas, dentistas y consultorios": "🩺",
    "Retail & e-commerce": "🛍️",
    "Retail y e-commerce": "🛍️",
    "Fintech & banking": "💳",
    "Fintech y banca": "💳",
    "Public offices": "🏛️",
    "Oficinas públicas": "🏛️",
  };

  const handleScrollToUseCases = () => {
    if (typeof document !== "undefined") {
      document.getElementById("use-cases")?.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <div className="space-y-24 pb-16 px-4 sm:px-6 lg:px-8 md:space-y-32">
      {/* Hero */}
      <section className="pt-16 pb-20 md:pt-20 md:pb-28">
        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-900 via-slate-800 to-onDutyNavy">
          <div className="absolute inset-0 opacity-50">
            <div className="absolute left-10 top-16 h-40 w-40 rounded-full bg-onDutyGold/40 blur-3xl" />
            <div className="absolute bottom-10 right-10 h-56 w-56 rounded-full bg-onDutyWine/40 blur-3xl" />
          </div>
          <div className="relative mx-auto grid max-w-6xl items-center gap-10 px-4 py-10 sm:px-6 md:py-14 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)] lg:px-8">
            <div className="text-white">
              <div className="inline-flex items-center rounded-full bg-amber-100 px-3 py-1 text-xs font-medium uppercase tracking-wide text-amber-900 dark:bg-amber-900/30 dark:text-amber-200">
                {lang === "en" ? "Always-on AI agents" : "Agentes de IA siempre de turno"}
              </div>
              <h1 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl md:text-5xl">{c.heroTitle}</h1>
              <p className="mt-4 max-w-2xl text-base text-slate-100 md:text-lg">{c.heroSubtitle}</p>
              <div className="mt-6 flex flex-wrap items-center gap-3">
                <PrimaryButton href="/try">{c.heroPrimaryCtaTry}</PrimaryButton>
                <PrimaryButton href="/signup" className="bg-onDutyWine hover:border-onDutyWine hover:text-onDutyWine">
                  {c.heroPrimaryCtaSignup}
                </PrimaryButton>
                <SecondaryButton
                  onClick={handleScrollToUseCases}
                  className="border-white text-white hover:border-onDutyGold hover:bg-onDutyGold hover:text-onDutyNavy"
                >
                  {c.heroSecondaryLink}
                </SecondaryButton>
              </div>
              <div className="mt-3 grid gap-3 text-xs text-slate-100 sm:grid-cols-2">
                <p>{c.heroPrimaryCtaTrySub}</p>
                <p>{c.heroPrimaryCtaSignupSub}</p>
              </div>
            </div>

            <div className="relative">
              <div className="absolute -right-6 -top-8 h-24 w-24 rounded-full bg-onDutyGold/40 blur-3xl" />
              <div className="relative rounded-3xl border border-white/15 bg-white/85 p-6 shadow-2xl backdrop-blur dark:border-slate-800 dark:bg-slate-900/80">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-300">OnDuty Dashboard</p>
                    <p className="text-xl font-semibold text-onDutyNavy dark:text-white">Live overview</p>
                  </div>
                  <span className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-100">
                    <span className="h-2 w-2 rounded-full bg-emerald-500" aria-hidden />
                    {lang === "en" ? "Online" : "En línea"}
                  </span>
                </div>

                <div className="mt-6 grid gap-3 sm:grid-cols-3">
                  {["Leads captured", "Conversations", "Avg. response"].map((label, idx) => (
                    <div
                      key={label}
                      className="rounded-2xl border border-slate-200/80 bg-white/80 p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900/70"
                    >
                      <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</p>
                      <p className="text-xl font-semibold text-onDutyNavy dark:text-white">
                        {idx === 0 ? "2,341" : idx === 1 ? "8,120" : "12s"}
                      </p>
                      <p className="text-xs text-emerald-600 dark:text-emerald-300">{idx === 2 ? "↗" : "+28%"}</p>
                    </div>
                  ))}
                </div>

                <div className="mt-6 space-y-3 rounded-2xl border border-slate-200/80 bg-gradient-to-r from-slate-50 to-white p-4 shadow-sm dark:border-slate-800 dark:from-slate-900 dark:to-slate-900/80">
                  <div className="flex items-start gap-2">
                    <div className="mt-1 h-2 w-2 rounded-full bg-slate-400" aria-hidden />
                    <div>
                      <p className="text-xs font-semibold text-slate-500">Guest</p>
                      <p className="text-sm text-slate-700 dark:text-slate-200">Hi, can I check in after midnight?</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-2">
                    <div className="mt-1 h-2 w-2 rounded-full bg-onDutyGold" aria-hidden />
                    <div>
                      <p className="text-xs font-semibold text-slate-500">OnDuty Agent</p>
                      <p className="text-sm text-slate-700 dark:text-slate-200">
                        Absolutely—late check-in is available. I can also share parking and Wi-Fi info now.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Who it's for */}
      <section className="mx-auto max-w-6xl rounded-3xl border border-slate-200/70 bg-white/80 p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/80">
        <div className="flex flex-wrap items-center justify-center gap-3 text-sm font-semibold text-onDutyNavy dark:text-white">
          {c.whoForItems.map((label) => (
            <span key={label} className="rounded-full border border-slate-200 bg-white px-4 py-2 shadow-sm dark:border-slate-700 dark:bg-slate-800">
              {label}
            </span>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="features" className="mx-auto max-w-6xl space-y-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.howTitle}</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">{t.features.subheading}</p>
        </div>
        <div className="grid gap-6 md:grid-cols-3">
          {c.howSteps.map((item, idx) => (
            <div
              key={item.title}
              className="flex h-full flex-col rounded-2xl border border-slate-200/80 bg-white/80 p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md dark:border-slate-800 dark:bg-slate-900/80"
            >
              <div className="flex items-center gap-2 text-xs font-semibold text-onDutyGold">
                <span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-onDutyGold/20 text-onDutyNavy">{idx + 1}</span>
                {lang === "en" ? "Step" : "Paso"} {idx + 1}
              </div>
              <p className="mt-2 text-lg font-semibold text-onDutyNavy dark:text-white">{item.title}</p>
              <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{item.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Why OnDuty */}
      <section className="mx-auto max-w-6xl space-y-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.whyTitle}</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">{t.features.subheading}</p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {c.whyFeatures.map((item) => (
            <div
              key={item.title}
              className="flex h-full flex-col gap-2 rounded-2xl border border-slate-200/80 bg-white/80 p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/80"
            >
              <div className="flex items-center gap-2 text-lg font-semibold text-onDutyNavy dark:text-white">
                <span aria-hidden className="text-xl">
                  {item.title.includes("24/7")
                    ? "🌙"
                    : item.title.includes("support") || item.title.includes("soporte")
                      ? "💬"
                      : item.title.includes("Multi")
                        ? "🌐"
                        : item.title.includes("Analytics") || item.title.includes("Analítica")
                          ? "📊"
                          : item.title.includes("Human") || item.title.includes("humano")
                            ? "🤝"
                            : "🧱"}
                </span>
                {item.title}
              </div>
              <p className="text-sm text-slate-600 dark:text-slate-300">{item.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Use cases */}
      <section id="use-cases" className="mx-auto max-w-6xl space-y-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.useCasesTitle}</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">
            {lang === "en" ? "Answer the questions that slow you down." : "Responde las dudas que frenan a tus clientes."}
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {c.useCases.map((item) => (
            <div
              key={item.title}
              className="flex h-full flex-col rounded-2xl border border-slate-200/80 bg-white/70 p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md dark:border-slate-800 dark:bg-slate-900/70"
            >
              <span className="mb-3 text-2xl" aria-hidden>
                {useCaseIcons[item.title] ?? "✨"}
              </span>
              <div className="flex-1 space-y-2">
                <h3 className="text-lg font-semibold text-onDutyNavy dark:text-white">{item.title}</h3>
                <ul className="space-y-1 text-sm text-slate-600 dark:text-slate-300">
                  {item.bullets.map((bullet) => (
                    <li key={bullet} className="flex items-start gap-2">
                      <span>•</span>
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="mt-4 pt-2">
                <SecondaryButton href="/use-cases" className="w-full justify-center">
                  {lang === "en" ? "Explore this use case" : "Ver este caso de uso"}
                </SecondaryButton>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Analytics */}
      <section id="analytics" className="py-16 md:py-24">
        <div className="mx-auto grid max-w-6xl items-start gap-10 px-2 sm:px-0 lg:grid-cols-2">
          <div>
            <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.analyticsTitle}</h2>
            <p className="mt-3 text-lg text-slate-600 dark:text-slate-300">{c.analyticsIntro}</p>
            <ul className="mt-6 space-y-4">
              {c.analyticsBullets.map((item) => (
                <li key={item.title} className="flex gap-3">
                  <span className="mt-1 text-emerald-500" aria-hidden>
                    ●
                  </span>
                  <div>
                    <p className="font-medium text-slate-900 dark:text-slate-50">{item.title}</p>
                    <p className="text-sm text-slate-600 dark:text-slate-300">{item.text}</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900/80">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs uppercase tracking-widest text-slate-500">Workspace overview</p>
                <p className="text-lg font-semibold text-onDutyNavy dark:text-white">Support & activity</p>
              </div>
              <span className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-900/50 dark:text-emerald-100">
                <span className="h-2 w-2 rounded-full bg-emerald-500" aria-hidden />
                {lang === "en" ? "Live" : "En vivo"}
              </span>
            </div>
            <div className="mt-5 grid gap-3 sm:grid-cols-2">
              {[
                {
                  label: lang === "en" ? "Conversations (30d)" : "Conversaciones (30d)",
                  value: "650",
                  helper: lang === "en" ? "last 30 days" : "últimos 30 días",
                },
                {
                  label: lang === "en" ? "Resolution rate" : "Tasa de resolución",
                  value: "94%",
                  helper: lang === "en" ? "steady" : "estable",
                },
              ].map((stat) => (
                <div key={stat.label} className="rounded-2xl border border-slate-200/80 bg-slate-50 p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                  <p className="text-xs uppercase tracking-wide text-slate-500">{stat.label}</p>
                  <p className="text-2xl font-semibold text-onDutyNavy dark:text-white">{stat.value}</p>
                  <p className="text-xs text-slate-600 dark:text-slate-300">{stat.helper}</p>
                </div>
              ))}
            </div>
            <div className="mt-5 space-y-3 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <p className="text-sm font-semibold text-onDutyNavy dark:text-white">
                {lang === "en" ? "Busiest hours" : "Horas pico"}
              </p>
              <div className="grid grid-cols-6 gap-2 text-xs text-slate-500 dark:text-slate-300">
                {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day, idx) => (
                  <div key={day} className="space-y-1">
                    <div
                      className="h-20 rounded-md bg-gradient-to-t from-slate-200 to-onDutyGold/70 dark:from-slate-800 dark:to-onDutyGold/40"
                      style={{ height: `${60 + idx * 4}px` }}
                    />
                    <p className="text-center">{day}</p>
                  </div>
                ))}
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-300">
                {lang === "en"
                  ? "Alerts when spikes or suspicious activity happens."
                  : "Alertas cuando hay picos o actividad sospechosa."}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Customer service vs sales */}
      <section className="mx-auto max-w-6xl space-y-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.csVsSalesTitle}</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">
            {lang === "en"
              ? "Stay responsive now and get early access to sales once messaging APIs are live."
              : "Sigue respondiendo hoy y obtén acceso anticipado a ventas cuando las APIs estén listas."}
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2">
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 shadow-sm dark:border-emerald-800/60 dark:bg-emerald-900/40">
            <div className="mb-2 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800 dark:bg-emerald-800 dark:text-emerald-100">
              {c.csCardTag}
            </div>
            <h3 className="text-xl font-semibold text-onDutyNavy dark:text-white">{c.csCardTitle}</h3>
            <div className="mt-3 space-y-2 text-sm text-slate-700 dark:text-slate-200">
              {splitList(c.csCardText).map((line) => (
                <p key={line}>{line}</p>
              ))}
            </div>
          </div>
          <div className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div className="mb-2 inline-flex items-center gap-2 rounded-full bg-slate-200 px-3 py-1 text-xs font-semibold text-slate-800 dark:bg-slate-800 dark:text-slate-100">
              {c.salesCardTag}
            </div>
            <h3 className="text-xl font-semibold text-onDutyNavy dark:text-white">{c.salesCardTitle}</h3>
            <div className="mt-3 space-y-2 text-sm text-slate-700 dark:text-slate-200">
              {splitList(c.salesCardText).map((line) => (
                <p key={line}>{line}</p>
              ))}
            </div>
            <SecondaryButton href="/signup?sales_waitlist=true" className="mt-4 justify-center">
              {c.salesComingCta}
            </SecondaryButton>
          </div>
        </div>
        <p className="text-sm text-slate-600 dark:text-slate-300">
          {lang === "en"
            ? "We’ll roll out sales agents once WhatsApp and Telegram integrations are ready. Enterprise customers get early access."
            : "Lanzaremos los agentes de ventas cuando las integraciones con WhatsApp y Telegram estén listas. Los clientes Enterprise tendrán acceso anticipado."}
        </p>
      </section>

      {/* Pricing */}
      <section id="pricing" className="mx-auto max-w-6xl space-y-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.pricingTitle}</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">{c.pricingSubtitle}</p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
          {c.pricingPlans.map((plan) => (
            <div
              key={plan.id}
              className={`flex h-full flex-col rounded-3xl border p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg${
                plan.popular
                  ? " border-onDutyGold bg-white/90 dark:border-onDutyGold dark:bg-slate-900"
                  : " border-slate-200 bg-white/90 dark:border-slate-800 dark:bg-slate-900"
              }`}
            >
              <div className="flex items-center justify-between">
                <h3 className="text-xl font-semibold text-onDutyNavy dark:text-white">{plan.name}</h3>
                {plan.popular && (
                  <span className="rounded-full bg-onDutyGold/90 px-3 py-1 text-xs font-semibold text-onDutyNavy">
                    {lang === "en" ? "Most popular" : "Más popular"}
                  </span>
                )}
              </div>
              <p className="mt-1 text-2xl font-bold text-onDutyNavy dark:text-white">{plan.price}</p>
              <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{plan.label}</p>
              <ul className="mt-4 space-y-2 text-sm text-slate-700 dark:text-slate-200">
                {plan.bullets.map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span>•</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <div className="mt-6 pt-4 border-t border-slate-200/70 dark:border-slate-800" />
              <div className="mt-4">
                {plan.ctaLabel ? (
                  <SecondaryButton href="mailto:hello@alwaysonduty.ai" className="w-full justify-center">
                    {plan.ctaLabel}
                  </SecondaryButton>
                ) : (
                  <PrimaryButton href={`/signup?plan=${plan.id}`} className="w-full justify-center">
                    {c.heroPrimaryCtaSignup}
                  </PrimaryButton>
                )}
              </div>
            </div>
          ))}
        </div>

        <div className="space-y-3 rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
          <h3 className="text-2xl font-semibold text-onDutyNavy dark:text-white">{c.salesComingTitle}</h3>
          <div className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
            {splitList(c.salesComingText).map((line) => (
              <p key={line}>{line}</p>
            ))}
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            {[
              lang === "en" ? "Inbound lead capture" : "Captura de leads en chat",
              lang === "en" ? "Follow-up sequences" : "Secuencias de seguimiento",
              lang === "en" ? "Pipeline handoff to your CRM" : "Entrega al CRM o equipo de ventas",
            ].map((item) => (
              <div key={item} className="rounded-xl border border-slate-200 bg-white/90 p-4 text-onDutyNavy shadow-sm dark:border-slate-800 dark:bg-slate-800 dark:text-white">
                {item}
              </div>
            ))}
          </div>
          <SecondaryButton href="/signup?sales_waitlist=true" className="mt-4 w-full justify-center sm:w-auto">
            {c.salesComingCta}
          </SecondaryButton>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-6xl space-y-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-onDutyNavy dark:text-white">{c.faqTitle}</h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">
            {lang === "en" ? "Clear answers before you commit." : "Respuestas claras antes de decidir."}
          </p>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          {c.faqItems.map((item) => (
            <div key={item.question} className="rounded-2xl border border-slate-200 bg-white/90 p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <h3 className="text-lg font-semibold text-onDutyNavy dark:text-white">{item.question}</h3>
              <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{item.answer}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section className="mx-auto max-w-6xl rounded-3xl border border-slate-200 bg-gradient-to-r from-onDutyNavy to-onDutyWine p-8 text-white shadow-xl dark:border-slate-800">
        <div className="flex flex-col items-start gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm uppercase tracking-[0.2em] text-onDutyGold">Always-on coverage</p>
            <h3 className="text-2xl font-semibold">{c.finalCtaTitle}</h3>
            <p className="mt-2 text-sm text-slate-100">{c.finalCtaText}</p>
          </div>
          <div className="flex flex-wrap gap-3">
            <PrimaryButton href="/try">{c.finalCtaPrimary}</PrimaryButton>
            <SecondaryButton
              href="/signup"
              className="border-white text-white hover:border-onDutyGold hover:bg-onDutyGold hover:text-onDutyNavy"
            >
              {c.finalCtaSecondary}
            </SecondaryButton>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="mx-auto max-w-6xl border-t border-slate-200 pt-8 text-sm text-slate-600 dark:border-slate-800 dark:text-slate-300">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p>© {new Date().getFullYear()} OnDuty. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:text-onDutyNavy dark:hover:text-onDutyGold">
              {t.footer.privacy}
            </Link>
            <Link href="#" className="hover:text-onDutyNavy dark:hover:text-onDutyGold">
              {t.footer.terms}
            </Link>
            <Link href="#" className="hover:text-onDutyNavy dark:hover:text-onDutyGold">
              {t.footer.contact}
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
